apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: laq-server
spec:
  replicas: 1
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: laq-server
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: laq-server
    spec:
      # 定义容器，可以多个
      containers:
      - name: laq-server # 容器名字
        image: registry.cn-hangzhou.aliyuncs.com/linxiaoyi/laq-server:latest # 镜像
        env:
          - name: GITHUB_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: laq-server-secret
                key: github_access_token
                optional: true
          - name: GITHUB_OWNER
            valueFrom:
              configMapKeyRef:
                name: laq-server-config
                key: github_owner
          - name: GITHUB_REPO
            valueFrom:
              configMapKeyRef:
                name: laq-server-config
                key: github_repo
